# Generated by Django 5.1.7 on 2025-04-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_category_tags_image_description_image_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_wishlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='purchase_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
