# Generated by Django 5.1.7 on 2025-04-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_financialinfo_profilestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
