# Generated by Django 5.1.7 on 2025-04-22 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_category_is_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_spending', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spending_cushion', models.BooleanField(default=False)),
                ('cushion_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.financialinfo')),
            ],
        ),
    ]
