# Generated by Django 5.1.7 on 2025-04-22 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='financial_info',
        ),
        migrations.AddField(
            model_name='goal',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.userprofile'),
        ),
    ]
