# Generated by Django 5.1.7 on 2025-04-22 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_goal_financial_info_goal_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='user_profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.userprofile'),
        ),
    ]
